name: release

on:
  push:
    tags:
      - test*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Convert yaml to json
        run: python .github/workflows/lib/yaml_to_json.py resources/referers.yml referers.json
      - name: Get datetime
        id: datetime
        run: echo "datetime=$(date "+%Y-%m-%d-%H%M%S")" >> $GITHUB_OUTPUT
      - name: Tag
        run: git tag ${{ steps.datetime.outputs.datetime }} && git push --tags
      - name: Create GitHub release and attach referers.json
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.datetime.outputs.datetime }}
          files: ./referers.json
